#!/bin/sh

set -eu

send_everything_to_bootserver() {
  cat <<'EOF' > /etc/syslog-ng/conf.d/send_everything_to_bootserver.conf
destination d_bootserver { tcp("syslog"); };
log { source(s_src); destination(d_bootserver); };
EOF
  rm -f /etc/syslog-ng/conf.d/send_some_to_bootserver_with_cache.conf
}

send_session_data_to_bootserver_with_cache() {
  rm -f /etc/syslog-ng/conf.d/send_everything_to_bootserver.conf

  read puavo_domain < /etc/puavo/domain
  cat <<EOF > /etc/syslog-ng/conf.d/send_some_to_bootserver_with_cache.conf
destination d_bootserver {
  tcp("syslog.${puavo_domain}"
      disk-buffer(
        reliable(yes)
        mem-buf-size(1000000)
        disk-buf-size(200000000)
      )
  );
};

filter sessions {
     program('puavo-login')
  or (program('sshd')
       and match('session (opened|closed)', value('MESSAGE')))
  or (program('systemd')
       and match('^(Started|Starting|Stopping|Stopped) Session', value('MESSAGE')))
  or program('systemd-logind')
};

log {
  source(s_src);
  filter(sessions);
  destination(d_bootserver);
};
EOF
}

logging_policy="$(puavo-conf puavo.admin.logging.policy)"

case "$logging_policy" in
  local-only)
    rm -f /etc/syslog-ng/conf.d/send_everything_to_bootserver.conf \
          /etc/syslog-ng/conf.d/send_some_to_bootserver_with_cache.conf
    ;;
  send-everything-to-bootserver)
    send_everything_to_bootserver
    ;;
  send-session-data-to-bootserver-with-cache)
    send_session_data_to_bootserver_with_cache
    ;;
  *)
    echo "Unsupported logging policy: ${logging_policy}" >&2
    exit 1
    ;;
esac

exit 0
