#!/bin/sh

set -eu

pam_install() {
  install -m 644 -o root -g root "$@"
}

pam_install /etc/puavo-conf/files/etc/pam.d/gdm-autologin \
            /etc/pam.d/gdm-autologin

pam_install /etc/puavo-conf/files/etc/pam.d/gdm-password \
            /etc/pam.d/gdm-password

pam_install /etc/puavo-conf/files/etc/pam.d/i3lock \
            /etc/pam.d/i3lock

pam_install /etc/puavo-conf/files/etc/pam.d/slock \
            /etc/pam.d/slock

pam_install /etc/puavo-conf/files/etc/pam.d/sudo \
            /etc/pam.d/sudo

# XXX get rid of hosttype handling
hosttype=$(puavo-conf puavo.hosttype)
case "$hosttype" in
  fatclient|laptop)
    pam_install "/etc/puavo-conf/files/etc/pam.d/puavo-account-${hosttype}" \
                /etc/pam.d/puavo-account
    pam_install "/etc/puavo-conf/files/etc/pam.d/puavo-auth-${hosttype}" \
                /etc/pam.d/puavo-auth
    pam_install "/etc/puavo-conf/files/etc/pam.d/puavo-session-${hosttype}" \
                /etc/pam.d/puavo-session

    pam_install "/etc/puavo-conf/files/etc/pam.d/puavo-cached-auth" \
                /etc/pam.d/puavo-cached-auth
    ;;
esac
