#!/bin/sh

set -eu

if [ -e /run/puavo/nbd-server ]; then
  cat <<'EOF' > /etc/syslog-ng/conf.d/send_everything_to_bootserver.conf
destination d_bootserver { tcp("syslog"); };
log { source(s_src); destination(d_bootserver); };
EOF
else
  rm -f /etc/syslog-ng/conf.d/send_everything_to_bootserver.conf
fi
