#!/bin/sh

set -eu

status=0

# XXX We might want to do this, but the operation is pointless in the
# XXX general case (and likely breaks some things currently!).
# XXX It is only needed when puavo-pkgs are not in the image itself,
# XXX or in the "smartboard"- and "ti-nspire-cx-cas-ss"-cases (see below).
# puavo-pkg reconfigure --all

PUAVO_PKG_CACHEDIR=/var/cache/puavo-pkg
PUAVO_PKG_ROOTDIR=/var/lib/puavo-pkg

. /etc/puavo-pkg/puavo-pkg.conf

get_puavopkg_state() {
  cat "${PUAVO_PKG_ROOTDIR}/packages/${1}/installed/.state" 2>/dev/null \
    || echo uninstalled
}

maybe_configure_package() {
  pkgname=$1
  puavoconf_key=$2

  case "$(get_puavopkg_state "$pkgname")" in
    configured)
      if [ "$(puavo-conf "$puavoconf_key") != 'true' ]; then
        puavo-pkg unconfigure "$pkgname" || return 1
      fi
      ;;
    uninstalled)
      ;;
    *)
      # package is installed but not configured
      if [ "$(puavo-conf "$puavoconf_key") = 'true' ]; then
        puavo-pkg configure "$pkgname" || return 1
      fi
      ;;
  esac

  return 0
}

# Instead, we now only do this, because smartboard should be
# configured/unconfigured based on puavo-conf variable
# "puavo.nonfree.smartboard.enabled".
maybe_configure_package smartboard puavo.nonfree.smartboard.enabled \
  || status=1

# ti-nspire-cx-cas-ss should be configured/unconfigured based on
# puavo-conf variable "puavo.nonfree.ti_nspire_cx_cas_ss.enabled".
maybe_configure_package ti-nspire-cx-cas-ss \
                        puavo.nonfree.ti_nspire_cx_cas_ss.enabled \
  || status=1

exit $status
